CLASS zcl_31_vat_indicator_ranv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA: vat_indicator TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_31_VAT_INDICATOR_RANV IMPLEMENTATION.
ENDCLASS.
