CLASS zcl_lab_39_budget_ranv DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS get_budget ABSTRACT RETURNING VALUE(rv_budget) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_39_BUDGET_RANV IMPLEMENTATION.
ENDCLASS.
