CLASS zcl_lab_70_observer_ranv DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS on_new_article ABSTRACT
      FOR EVENT new_article OF zcl_lab_69_blog_ranv
      IMPORTING ev_new_article.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_70_OBSERVER_RANV IMPLEMENTATION.
ENDCLASS.
