CLASS zcl_lab_29_organization_ranv DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS get_location ABSTRACT RETURNING VALUE(rv_location) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_29_ORGANIZATION_RANV IMPLEMENTATION.
ENDCLASS.
