CLASS zcl_lab_40_actual_budget_ranv DEFINITION INHERITING FROM zcl_lab_39_budget_ranv
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_budget REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_40_ACTUAL_BUDGET_RANV IMPLEMENTATION.


  METHOD get_budget.
    rv_budget = 'Actual Budget'.
  ENDMETHOD.
ENDCLASS.
