CLASS zcl_33_record_ranv DEFINITION INHERITING FROM zcl_32_constr_cntr_ranv
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_33_RECORD_RANV IMPLEMENTATION.
ENDCLASS.
