CLASS zcx_lab_56_no_date_ranv DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_LAB_56_NO_DATE_RANV IMPLEMENTATION.
ENDCLASS.
