CLASS zcx_52_exception2_ranv DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_52_EXCEPTION2_RANV IMPLEMENTATION.
ENDCLASS.
