CLASS zcx_51_exception1_ranv DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCX_51_EXCEPTION1_RANV IMPLEMENTATION.
ENDCLASS.
